name: Build, test and lint Node.js Package

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
      - '**'

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]];
          then
            echo "${{ github.event.head_commit.message }} is a release branch";
          else
            echo "${{ github.event.head_commit.message }} is not a release branch";
          fi

  build-test-lint:
    name: "Build, Test and Lint Node.js Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run lint
