name: Build, test and lint Node.js Package

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
      - '**'

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ github.ref_name }} =~ ^(?!\d+\.\d+\.\d+).*$ ]];
          then
            echo "This is not a release branch";
          else
            echo "This is a release branch";
          fi

  build-test-lint:
    name: "Build, Test and Lint Node.js Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run lint
