name: Run Test with Coverage Report and upload it to Github Pages

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
      - '**'

jobs:
  is-release-commit:
    uses: ./.github/workflows/is-release-commit.yml
    with:
      commit-message: ${{ github.event.head_commit.message }}

  test-coverage:
    name: "Run Test with Coverage Report"
    runs-on: ubuntu-latest
    needs: is-release-commit
    if: needs.is-release-commit.outputs.IS_RELEASE_COMMIT == 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
      - uses: actions/upload-pages-artifact@v3
        with:
          path: coverage/

  deploy-coverage-report:
    name: "Deploy Coverage Report to Github Pages"
    needs: test-coverage
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
