name: Run Test with Coverage Report and upload it to Github Pages

on:
  push:
    branches:
     - '![0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '**'

jobs:
  test-coverage:
    name: "Run Test with Coverage Report"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
      - uses: actions/upload-pages-artifact@v3
        with:
          path: coverage/

  deploy-coverage-report:
    name: "Deploy Coverage Report to Github Pages"
    needs: test-coverage
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
